

cy.on("uncaught:exception", (_, __) => {
    return false;
});